services:
  project-next:
    image: project-next:latest
    build: .
    container_name: project-next
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - project-next-network

  nginx:
    image: nginx:alpine
    container_name: fatura-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - project-next
    networks:
      - project-next-network

networks:
  project-next-network:
    driver: bridge
